### ISSUE TITLE
Add doc

### ISSUE THREAD

**Issue by Phyks** [Kerl13/AsciiMath#1]

**Comment by Kerl13** [comment]
Yop,

My bad… I've just added the minimum "how to use" in the README so you won't have to guess how it works !

I will soon write a description of the exact behaviour of the compiler. I let the issue opened till then

--Kerl

**Comment by Kerl13** [comment]
Better like that ?

**Comment by Phyks** [comment]
Sure! I will complete the doc whenever I find anything useful to add.
