### ISSUE TITLE
Floats division produce incorrect frac

### ISSUE THREAD

**Issue by fordarian** [Kerl13/AsciiMath#19]
`echo "1.3/1.2 " | asciimath ` => `1.\frac{3}{1}.2` instead of `\frac{1.3}{1.2}`

**Comment by Kerl13** [comment]
Thanks for your feedback :slightly_smiling_face:
Real numbers were not supported at all. That's been fixed in 6c204f32298ebdf4f2cd395af8fc39328565ded4
